name: CI
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: v12.x
      - run: npm install

  build:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - run: npm run build
      - run: npm run package


  sonar:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v1
      - name: Run sonar-scanner
        env:
          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}

#  test:
#    needs: build
#    jobs:
#    - run: npm test
#      env:
#        CI: true
